version: '3.2'
services:
  mediawiki:
    image: debian-mediawiki
    container_name: mediawiki
    restart: always
    ports:
      - 80:80
      - 9001:9001
    links:
      - pg
    depends_on:
      - pg
    volumes:
      - wikidata:/var/www/mediawiki
      #- ./LocalSettings.php:/var/www/mediawiki/LocalSettings.php
      #- ./wiki.png:/var/www/mediawiki/resources/assets/wiki.png:ro
    environment:
      MEDIAWIKI_DB_TYPE: postgres
      MEDIAWIKI_DB_HOST: pg
      MEDIAWIKI_DB_USER: wiki
      MEDIAWIKI_DB_PASSWORD: wiki
      MEDIAWIKI_DB_NAME: wiki
  pg:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wiki
      POSTGRES_PASSWORD: wiki
    volumes:
      - wikidb:/var/lib/postgresql/data

volumes:
  wikidata:
  wikidb:
